// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yubivxhdrtqihimyqylz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1Yml2eGhkcnRxaWhpbXlxeWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTI3OTMsImV4cCI6MjA2MTA2ODc5M30.PrxAFBSTde3NJPOMb39erVs8QmLqaCelD2oEM3SYAZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);